### PR TITLE
Update to v3 of the quandl api

### LINKED ISSUE #82: Switch to api version 3
Quandl is no longer maintaining version 1 of its api, which this package is written around so it will be time to make the switch.

### LINKED ISSUE #93: from and to don't appear to be working
I can't quite tell if I am doing this wrong, but it seems that the `from` and `to` options do not work. I looked at the code, and I think I am doing the right thing.

````
julia> quandl("GOOG/NYSE_AEB", from="2009-03-01", to="2009-03-30", rows=10)
2533x5 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2005-12-22 to 2015-12-24

             Open     High     Low      Close    Volume        
2005-12-22 | 24.95    25.15    24.88    25.0     240000        
2005-12-23 | 24.99    25.0     24.88    25.0     12200         
2005-12-27 | 25.0     25.07    24.9     24.9     20600         
2005-12-28 | 24.95    25.0     24.9     25.0     13300         
⋮
2015-12-21 | 23.44    23.75    23.39    23.65    22943         
2015-12-22 | 23.66    23.78    23.6     23.66    18245         
2015-12-23 | 23.68    23.97    23.55    23.88    17301         
2015-12-24 | 23.69    24.07    23.67    24.07    9927          
````

### PR DESCRIPTION
**Pull request by ViralBShah**
Fix directory creation on Windows
Update to v3 of the Quandl API
Fix #82
Fix #93

### CODE REVIEW

**Comment by ViralBShah** [comment]
One other change is that the api key is no longer written to file. Should we reinstate that?

**Comment by milktrader** [comment]
So this call doesn't work?

julia> set_auth_token("myauthtoken") # if you choose to use your unique Quandl.com token

**Comment by milktrader** [comment]
I'll merge this and then we can fix the API key separately

**Comment by ViralBShah** [comment]
Thanks. I am not too familiar with Quandl APIs. I just started with your package and did what I had to for getting it to work.

**Comment by ViralBShah** [comment]
Yes, the auth token phrase didn't work, and I don't know if it was just a name change, or even a change in the way the api key works now. This is perhaps worth tagging a new version for.

I also realized that we probably need to support better error handling.

**Comment by milktrader** [comment]
I'll tag this since tests are passing.

**Pull request merged**
