### PR TITLE
Create auth_token automatically

### PR DESCRIPTION
**Pull request by brk00**
If there is no auth token file, create an empty one when loading the module. Also renames `auth_token.jl` to `auth_token`, since it's not a julia file.

### CODE REVIEW

**Comment by milktrader** [comment]
Didn't we change this approach because of issues we had with explicitly creating an auth_token file in the first place ... need to comb over some previous commits

**Comment by milktrader** [comment]
This is the current api, why would we change this?

````md
Before you can download data, you need to generate a file to hold your download token. This can be manually added but preferably done with the set_auth_token method.

julia> set_auth_token("") # if you choose to use anonymous calls

julia> set_auth_token("myauthtoken") # if you choose to use your unique Quandl.com token
````

**Comment by brk00** [comment]
The previous method was to have an empty auth_token when installing package. This made the package dirty. Now we have to create a auth_token file by hand. It would be much simpler if it wasn't required since, as noticed on #73, many users skip this step (or simply ignore README).

With this PR, the package is not dirty (since there is no dummy file) and no action is required from the user before usage.

**Comment by milktrader** [comment]
So you're creating a default empty string for the token with this file, and then providing the `set_auth_token()` method to add one if desired?

**Comment by brk00** [comment]
Yes, exactly. Whenever the Module is imported, it checks for the existence of an `auth_token` file. If it doesn't exist, it creates an empty one, calling `set_auth_token("")`.

**Comment by milktrader** [comment]
Ok, sounds like a good idea then. Can you write a test for it?

**Comment by brk00** [comment]
Of course! I'm not very sure what to test though. The existence of an auth token after importing the module?

**Comment by brk00** [comment]
Done. Also added validity check for auth tokens: they must be empty or 20 chars long (according to Quandl team).

**Comment by milktrader** [comment]
This is passing Travis for stable, but not nightlies, still failing on the HDF5 bug for v0.4.

**Pull request merged**
