### PR TITLE
swap to https

### PR DESCRIPTION
**Pull request by markthompson676**
Hi,  I think there's been a recent change to quandl which requires https rather than http connections.  These simple changes to your code worked for me.  Thanks, Mark.

### CODE REVIEW

**Comment by milktrader** [comment]
Does this eliminate anonymous downloading?

**Comment by milktrader** [comment]
Tests failing on nightlies, I'll need to look into that separately though. This PR makes the package functional again. Thanks!

**Comment by markthompson676** [comment]
I don't believe so.

**Comment by milktrader** [comment]
It doesn't affect anonymous downloading.

**Pull request merged**
